CREATE SCHEMA "rooftop-backend-challenge"
    AUTHORIZATION postgres;
    
CREATE TABLE "rooftop-backend-challenge".coupons
(
    assigned_at timestamp,
    code character(8),
    customer_email character varying,
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    expires_at timestamp NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE "rooftop-backend-challenge".coupons
    OWNER to postgres;

CREATE TABLE "rooftop-backend-challenge".stores
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    name character varying,
    address character varying,
    PRIMARY KEY (id)
);

ALTER TABLE "rooftop-backend-challenge".stores
    OWNER to postgres;


INSERT INTO "rooftop-backend-challenge".coupons (code, customer_email, assigned_at, expires_at) VALUES
('H37VUSZS','abmem@vuec.ps','2022-05-29 20:03:46','2022-05-29 20:03:46'),
('AQEFXLBY',NULL,NULL,'2022-06-08 02:16:15'),
('DKQTZVWV','uf@cuze.cw','2021-07-22 18:36:18','2021-12-01 12:15:26'),
('OQTHMFQP','te@wobi.np','2021-07-16 16:12:17','2022-01-20 12:43:12'),
('KKBV0JWL',NULL,NULL,'2021-10-15 02:23:01'),
('F4HPVGGW','hizo@fo.sd','2021-07-22 18:05:39','2021-09-18 20:29:10'),
('SK3E1CAT',NULL,NULL,'2021-11-14 21:35:52'),
('FVEPTYGE',NULL,NULL,'2021-09-15 12:03:20'),
('1HSYNH4I',NULL,NULL,'2022-05-29 00:20:51'),
('3HMXGF06',NULL,NULL,'2022-05-11 18:08:49'),
('PFOJBHTL',NULL,NULL,'2022-05-06 14:03:28'),
('YE1YKMRW','ku@igcikuv.mg','2021-07-15 08:37:02','2022-07-25 07:42:58'),
('QZCMVMLR',NULL,NULL,'2021-11-10 20:56:59'),
('RYPPPUSV',NULL,NULL,'2022-05-27 18:57:19'),
('PUAKJ3LZ','izi@sanen.dk','2021-07-16 01:29:35','2022-01-11 19:46:57'),
('2DMVHQU5',NULL,NULL,'2021-09-11 02:20:06'),
('QOSR5N3X','hunje@wuvum.mz','2021-07-24 09:13:05','2022-01-31 00:22:01'),
('B3ZZS71E',NULL,NULL,'2022-03-14 20:37:38'),
('FGW7VGG7',NULL,NULL,'2022-07-16 19:48:53'),
('ZIOO7RIQ',NULL,NULL,'2022-01-18 23:31:13'),
('SGHJBRMF',NULL,NULL,'2022-05-02 06:35:55'),
('DVARUZY0',NULL,NULL,'2021-08-29 06:56:37'),
('PHQNO8VX','co@waalamis.fi','2021-07-21 02:04:16','2022-01-09 06:26:16'),
('1UC3MGIY',NULL,NULL,'2022-01-27 01:01:40'),
('QVLYWPKU','jihvoso@admip.pn','2021-07-13 10:29:23','2022-07-12 08:07:17'),
('Z4FLWXAT','di@bemroeba.al','2021-07-18 20:24:23','2022-05-31 10:31:29'),
('QDMT776Y','afejoj@sis.tm','2021-07-27 03:48:55','2021-10-26 12:55:27'),
('G67OXFRX',NULL,NULL,'2021-09-02 10:19:37'),
('BZEKXMDV','hiw@ga.eg','2021-07-20 20:11:24','2021-09-07 06:03:37'),
('KCWV8QBW','mogcawog@piznicaf.tf','2021-07-16 05:43:17','2021-09-25 00:14:24'),
('L7CXC8XM','cu@huwihsib.ge','2021-07-17 05:16:11','2021-10-22 22:11:24'),
('WZYBOOFA',NULL,NULL,'2022-05-16 07:49:36'),
('CY0TOWD7','hoipcun@uwsi.by','2021-07-16 10:42:13','2021-10-03 08:40:43'),
('SRSKK2MD',NULL,NULL,'2021-09-05 14:35:28'),
('PYAGKRBW',NULL,NULL,'2022-03-19 20:44:09'),
('3E88KDIH','lohbaek@pitsiew.ws','2021-07-23 13:42:30','2021-10-30 08:24:13'),
('2NWBXPRF','ki@otu.nu','2021-07-25 18:18:36','2021-11-20 23:54:18'),
('F1OJPVGX','ce@huc.gs','2021-07-17 05:31:35','2022-07-26 07:29:38'),
('MNFKDIND',NULL,NULL,'2022-07-25 16:50:35'),
('NL2KHREW',NULL,NULL,'2021-10-15 13:24:01'),
('VEGU8D2L',NULL,NULL,'2021-09-03 09:15:40'),
('YT6GKJYJ','wotef@ehe.do','2021-07-14 21:17:01','2022-06-18 09:27:47'),
('XFS22XPJ',NULL,NULL,'2022-01-16 00:30:12'),
('D1YKKU0Q',NULL,NULL,'2022-04-29 18:47:41'),
('ZONGGFRX','bonerid@maulma.ir','2021-07-23 01:40:55','2022-01-30 06:42:16'),
('18WLKCIP',NULL,NULL,'2022-06-22 18:47:03'),
('RIDDDEPS',NULL,NULL,'2021-10-26 09:19:58'),
('RY039V10',NULL,NULL,'2022-06-10 02:29:56'),
('MXWEQSVL','ma@hukoh.vc','2021-07-22 17:03:41','2022-05-21 05:10:25'),
('Z5OM8PDF',NULL,NULL,'2022-03-31 05:02:15'),
('MKDZ5JDU',NULL,NULL,'2021-12-19 00:14:18'),
('UULAJL9O',NULL,NULL,'2021-11-28 04:15:28'),
('8QKCC8AN',NULL,NULL,'2022-07-06 07:30:49'),
('NRGINPF7',NULL,NULL,'2022-07-20 23:38:42'),
('WMENEDGU','nutka@alobul.pt','2021-07-20 13:47:41','2021-12-04 14:17:41'),
('C3S7XNHV',NULL,NULL,'2022-05-22 02:02:39'),
('L0AF8EFU',NULL,NULL,'2022-06-10 12:06:22'),
('KY1K2WXQ','ho@ba.ge','2021-07-15 18:58:19','2021-08-21 10:12:34'),
('KUE1MMQA',NULL,NULL,'2022-05-29 00:39:08'),
('RU048ONG','ifir@debba.gu','2021-07-12 18:53:47','2022-05-08 14:10:52'),
('EKTSZEQU','cu@macavu.bt','2021-07-25 08:36:42','2021-07-31 17:34:11'),
('Z771TTBJ','do@zudgaru.mv','2021-07-18 22:51:55','2022-01-11 00:00:27'),
('EFZAX7XY','dah@mi.it','2021-07-20 18:12:11','2022-04-15 06:25:15'),
('IPKJK3WT',NULL,NULL,'2022-01-06 01:30:39'),
('IRB1VPKI',NULL,NULL,'2022-07-10 15:05:50'),
('WBAVWQZV','ul@si.ug','2021-07-23 19:04:13','2021-12-21 05:41:35'),
('OG1EGWKU','megpej@ciwuza.cl','2021-07-20 09:19:11','2022-04-06 06:35:25'),
('CJMOTDBD',NULL,NULL,'2021-10-16 02:43:19'),
('MVK1E9ZP','idgagako@asaebueje.ni','2021-07-14 07:01:05','2022-04-10 21:48:33'),
('8TEEKMVS',NULL,NULL,'2021-11-07 06:44:35'),
('NCDHCPIX','sah@cihtaef.sb','2021-07-27 08:14:15','2021-11-28 20:51:30'),
('WSCTMUNN','efjar@rarugvug.bs','2021-07-23 16:45:17','2021-11-20 19:40:03'),
('XZZIKUSX',NULL,NULL,'2021-11-06 12:44:25'),
('GLF7S4KD',NULL,NULL,'2022-04-23 07:40:28'),
('MLXPVRZ1','nilra@neimi.az','2021-07-16 04:26:21','2022-07-01 13:47:16'),
('MZQPQWXC','soted@umo.mk','2021-07-26 14:30:21','2022-02-01 23:18:31'),
('FG59CSBQ',NULL,NULL,'2021-11-06 18:49:32'),
('NRACQLHJ',NULL,NULL,'2022-03-25 18:13:45'),
('0WRGGEEY',NULL,NULL,'2022-07-05 22:28:42'),
('MCBSTEFG',NULL,NULL,'2021-12-07 02:54:33'),
('5BJYFGGR','vikduf@juf.ar','2021-07-22 23:42:04','2022-07-05 15:11:03'),
('MGIEGWPW',NULL,NULL,'2022-03-17 09:51:48'),
('2FWKYPCK',NULL,NULL,'2022-04-13 07:47:42'),
('VDYHWCHE','deped@micujed.gf','2021-07-21 10:40:28','2022-02-02 10:30:47'),
('DLQWZENR','lefikda@zogojse.wf','2021-07-23 19:27:52','2021-08-17 23:16:52'),
('6F5F49KK','nud@igomubfur.uy','2021-07-26 17:39:16','2021-12-08 09:27:11'),
('ONVLBHQY','rewdiz@sugrizag.ps','2021-07-14 04:01:47','2021-10-21 09:37:37'),
('SEVJNGUD',NULL,NULL,'2021-11-13 20:48:04'),
('S0YVFRYB',NULL,NULL,'2022-03-10 06:13:47'),
('ZGHFDIAF',NULL,NULL,'2022-06-30 07:34:25'),
('NDE39TVP','haceper@jepniat.pn','2021-07-24 15:29:05','2022-04-28 07:36:55'),
('MZPG3Z4Z','zekibni@suciko.gu','2021-07-23 23:07:00','2022-05-21 01:40:27'),
('CVBA9WF3',NULL,NULL,'2022-06-18 01:36:20'),
('WC1ZBIHF',NULL,NULL,'2022-03-15 20:50:23'),
('H6R38MYN','du@vo.uz','2021-07-17 00:04:13','2022-02-19 15:59:41'),
('DJCPL7QW','cac@ji.ae','2021-07-22 10:58:37','2022-03-18 05:43:54'),
('TZOL4BLA',NULL,NULL,'2022-06-29 07:07:47'),
('JGSBGVNJ',NULL,NULL,'2022-02-22 15:47:22'),
('OOVB3DMX','gew@av.pm','2021-07-18 03:44:53','2021-11-21 08:44:29'),
('TMBWTWW3','da@tuttuemo.fk','2021-07-26 20:53:29','2022-05-29 20:03:46'),
('1OLZVCDC',NULL,NULL,'2021-12-15 10:31:05');

INSERT INTO "rooftop-backend-challenge".stores (name, address) VALUES
('Service Corp. International','690 Kosbi Extension, Wonseika, RI, Armenia'),
('Amkor Technology, Inc.','1378 Enolut Pike, Atmevib, VT, St. Kitts & Nevis'),
('EOG Resources, Inc.','666 Nowal Heights, Lepijwu, ID, Malta'),
('Qwest Communications Intl Inc','1079 Ebicaj Center, Meawwod, KS, Northern Mariana Islands'),
('Alleghany Corporation','1372 Posli Key, Jisizuk, MI, New Zealand'),
('AT&T Corp.','1543 Buib Mill, Ubsaba, KS, Brunei'),
('Kerr-McGee Corporation','1064 Hucek Junction, Veonav, IA, Nepal'),
('McLeodUSA Incorporated','983 Hiza Road, Nipdodmu, MS, Cayman Islands'),
('CKE Restaurants Inc.','410 Tumov Square, Zarolol, NM, South Georgia & South Sandwich Islands'),
('E.I. Du Pont de Nemours and Company','889 Daifa Square, Kasowbol, VA, Western Sahara'),
('Beazer Homes USA, Inc.','1528 Gazet Court, Ligreri, WA, South Korea'),
('Foamex International Inc','233 Kincuk Highway, Bowofnoc, UT, Ascension Island'),
('Anthem, Inc.','190 Ducet Mill, Nutajum, WY, Tristan da Cunha'),
('Southern Company','327 Afiir Boulevard, Lilulaci, ID, Slovenia'),
('Republic Services Inc','1103 Sodo Avenue, Havtomij, MN, Russia'),
('PerkinElmer Inc','1441 Ehlir Square, Ziazouva, NE, Latvia'),
('Timken Company','1313 Jawob Circle, Itilefaje, MI, St. Lucia'),
('Silgan Holdings Inc.','1802 Vefice Park, Ovpokab, ME, Cayman Islands'),
('Payless Shoesource Inc','510 Adad Mill, Hudkogted, TN, Laos'),
('Belo Corp.','1871 Buhaj Mill, Ujuduzif, NM, Belize'),
('WPS Resources Corporation','1913 Hemzu River, Mejitwi, MN, Diego Garcia'),
('Sonic Automotive Inc.','1730 Fowtij Court, Jogposvi, MN, Seychelles'),
('Apartment Investment and Management Company','1597 Lidka Circle, Ejokisbam, NH, Bolivia'),
('Walt Disney Co','1928 Gegehi Place, Vejigo, NY, U.S. Virgin Islands'),
('Greif Bros. Corporation','212 Gozo Square, Sabeztoc, MA, Sweden'),
('SCI Systems Onc.','484 Ufse Trail, Becwakuf, NC, Dominican Republic'),
('Schering-Plough Corp','1289 Gidog Junction, Lafsuwwo, NE, Slovenia'),
('Family Dollar Stores Inc.','570 Acage Mill, Oviasen, HI, Taiwan'),
('Brunswick Corporation','1315 Giwacu Path, Huimman, CO, Cambodia'),
('ITT Industries Inc.','623 Torvi River, Winowsev, NM, China'),
('Goodrich Corporation','1094 Pawwud Square, Zabjikenu, NJ, Iraq'),
('J.B. Hunt Transport Services Inc.','1861 Jiwguh Place, Tutopcuf, WA, Micronesia'),
('Western Digital Inc','397 Tusted Plaza, Pahirze, WA, Martinique'),
('H&R Block Inc.','46 Curaf Grove, Lemhonhag, NH, Czech Republic'),
('Lucent Technologies Inc.','946 Suczij River, Bopigko, AZ, St. Helena'),
('General Cable Corporation','1320 Kuzma Heights, Hienmuz, MS, Dominican Republic'),
('Robert Half International Inc.','1331 Silbon Grove, Wiwevi, LA, Zimbabwe'),
('Genuity Inc.','5 Tomu Lane, Ecgalo, WY, Guyana'),
('New Jersey Resources Corporation','84 Pauni Junction, Paomaca, UT, Togo'),
('Providian Financial Corp.','1171 Fuwum Loop, Satowi, ID, Indonesia'),
('Ruddick Corp','540 Hila Avenue, Waruhnit, MA, Uzbekistan'),
('Puget Energy Inc.','901 Vitef Point, Parluhlo, IL, Mexico'),
('Advance Auto Parts, Inc.','591 Lugif Terrace, Patudoza, MD, Swaziland'),
('Packaging Corp. of America','43 Omija Path, Tibaup, MS, Laos'),
('Saks Inc','48 Eveeri Lane, Mawufa, NH, Azerbaijan'),
('Banta Corporation','1168 Asce Drive, Tidubga, NJ, Thailand'),
('Eaton Corporation','1063 Perso Place, Lomtuomu, TN, Central African Republic'),
('Kimberly-Clark Corporation','745 Hihpu Plaza, Nizedonet, RI, Guinea'),
('Scholastic Corp','1375 Cukis Highway, Edsojkep, MN, French Polynesia'),
('Precision Castparts Corp','1643 Hedlob Grove, Begjidon, NH, Malta'),
('MDU Resources Group Inc.','1479 Zozeta Ridge, Mowucaki, MA, Cuba'),
('Quanta Services Inc.','147 Uftek Center, Ebawofos, NC, Pitcairn Islands'),
('Texas Industries Inc.','670 Taoha Pass, Ihufce, OR, Guatemala'),
('Trigon Healthcare Inc.','1456 Bejno Turnpike, Wumgujun, UT, Mozambique'),
('Darden Restaurants Inc.','594 Fazudi Turnpike, Wecansij, ME, Cameroon'),
('Charter Communications Inc.','707 Dirke Circle, Potoccaj, NC, Lebanon'),
('Electronic Arts Inc.','1903 Ujne Square, Vulupem, PA, Kuwait'),
('Express Scripts Inc.','13 Olusa Point, Uhlafmu, OR, Libya'),
('The Allstate Corporation','1020 Odetik Glen, Rasovas, IN, Cocos (Keeling) Islands'),
('Ingram Micro Inc.','311 Cetvoh Way, Furacra, OH, French Polynesia'),
('Park Place Entertainment Corp','1944 Zuzaz Square, Ejelevume, NC, Northern Mariana Islands'),
('Hub Group Inc.','147 Mutrat Square, Pinusa, NV, Papua New Guinea'),
('Clear Channel Communications Inc.','505 Cerov Turnpike, Loemeleh, FL, Tonga'),
('Abercrombie & Fitch Co.','527 Iwebo Loop, Ajevjil, SC, Austria'),
('Prudential Financial Inc.','1492 Custe Ridge, Wigase, NV, Belgium'),
('OGE Energy Corp','146 Vasiv Mill, Luzsekter, MN, Togo'),
('Abercrombie & Fitch Co.','41 Uhopo Glen, Loghawhup, WY, Mauritania'),
('Del Monte Foods Co','1946 Naca Center, Zujazga, OK, Somalia'),
('Nacco Industries Inc','1516 Jubu Place, Paninul, AZ, Argentina'),
('Pittston Brinks Group','1189 Ukoege Street, Vunudowu, MS, Moldova'),
('Electronic Data Systems Corp.','78 Kivsuk Trail, Gewdecwi, NH, British Indian Ocean Territory'),
('Medtronic Inc.','743 Mawaze Loop, Petica, TN, Slovakia'),
('Applera Corporation','857 Eniso River, Nevcoafo, DE, Martinique'),
('Transocean Inc','1813 Dapuzo Place, Neribawar, VA, Taiwan'),
('Wm Wrigley Jr Company','1753 Kevlog Loop, Jaseufu, WA, Tanzania'),
('Autoliv, Inc.','351 Relib Path, Sehhawmub, ID, Central African Republic'),
('Pfizer Inc','24 Kubev Heights, Gufeun, VT, Mexico'),
('MBNA Corporation','1691 Fitum Extension, Jidemimi, GA, Mali'),
('Avnet, Inc.','196 Goba Court, Wishekol, WV, New Zealand'),
('Marsh Supermarkets Inc.','942 Limisa Square, Imogeki, TX, Mexico'),
('Hollywood Entertainment Corp.','503 Lohto Loop, Fukhihif, MI, Italy'),
('Dean Foods Company','575 Solo Terrace, Seruda, AK, Monaco'),
('Quanta Services Inc.','636 Izike Park, Mutabig, RI, Northern Mariana Islands'),
('Anadarko Petroleum Corporation','1916 Mafi Ridge, Tereni, NJ, Somalia'),
('Pioneer-Standard Electronics Inc.','147 Wabim Street, Debepmav, WI, Equatorial Guinea'),
('Longs Drug Stores Corporation','309 Jarkor Center, Wajpopbo, MO, Guinea'),
('Quanta Services Inc.','558 Naid Avenue, Panabe, IL, Papua New Guinea'),
('Vishay Intertechnology Inc','744 Cagris Point, Itogevu, HI, Cayman Islands'),
('GATX Corporation','1275 Fidah Manor, Huvenlil, VA, Martinique'),
('Spherion Corp','943 Wuwrar Trail, Udkavat, MT, Christmas Island'),
('Dial Corporation','184 Irci Pass, Hizaje, OH, Chile'),
('Avnet, Inc.','193 Burne Avenue, Migagezik, FL, Norway'),
('Administaff, Inc.','1939 Epeuc Grove, Zuseboh, SD, Aruba'),
('Quintiles Transnational','971 Kanaw Boulevard, Opeewota, VT, Antarctica'),
('Tech Data Corporation','1637 Adefo Highway, Tijinfot, MO, Austria'),
('Coca-Cola Co.','209 Hishes Key, Homilero, MD, Estonia'),
('Idacorp Inc.','1054 Ipama River, Jokkilaji, MA, Macedonia'),
('Eli Lilly and Company','412 Vemle Pass, Uzhuico, NH, Venezuela'),
('Gap Inc.','1707 Depar Avenue, Lewupzit, MD, Åland Islands'),
('J.P. Morgan Chase & Co.','1568 Veem Mill, Cududsiv, KS, Tristan da Cunha'),
('Toro Company','1435 Budej Circle, Izwehne, NJ, India'),
('Nash Finch Company','1353 Bujhu View, Peanwi, CA, Sudan'),
('AmerisourceBergen Corporation','1685 Erbu Court, Lelvajdeg, AR, Malaysia'),
('Henry Schein Inc.','750 Riza Parkway, Muwtijcim, PA, Qatar'),
('Bank of America Corporation','1055 Dofkal Ridge, Utravze, AK, Burkina Faso'),
('Allmerica Financial Corporation','216 Odigo River, Kacaneb, LA, Kenya'),
('Kimberly-Clark Corporation','845 Datvor Center, Wobevaza, SD, Bosnia & Herzegovina'),
('El Paso Corporation','484 Bebe Avenue, Falpiwali, VT, Sweden'),
('Charming Shoppes Inc.','1406 Kome Boulevard, Samuszeb, CT, Ceuta & Melilla'),
('Genzyme Corporation','159 Ubri Street, Abbuga, MT, Angola'),
('Stewart & Stevenson Services Inc','678 Jekwu View, Vikpusic, CT, Denmark'),
('IKON Office Solutions Inc.','216 Ehuop Ridge, Jasziziz, ND, Israel'),
('Merrill Lynch & Co. Inc.','1459 Vudod Center, Orakicdil, FL, Turks & Caicos Islands'),
('Health Net Inc.','442 Otva Glen, Rumfiug, MD, Uruguay'),
('Smurfit-Stone Container Corp','867 Magar Grove, Ifadagfa, IN, Tristan da Cunha'),
('La-Z-Boy Inc.','1983 Pinte Boulevard, Melmijfi, AR, Somalia'),
('CKE Restaurants Inc.','1732 Bufo Terrace, Todapoput, NE, Poland'),
('Volt Information Sciences Inc','1839 Lihit River, Uweciiri, DC, Rwanda'),
('Willamette Industries Inc.','1038 Mukka Glen, Jidowic, WI, Guadeloupe'),
('Jefferson-Pilot Co.','424 Kize Court, Folrira, MD, Armenia'),
('Applera Corporation','365 Zucmi Path, Isumuha, SD, Monaco'),
('Lands End Inc.','1863 Gatpi Grove, Wamabciw, IN, Gambia'),
('Yellow Corporation','504 Jafsu Drive, Cunorwu, DE, Hungary'),
('On Semiconductor Corp','382 Mare Key, Ugbuvar, WY, Sri Lanka'),
('Teradyne Inc','752 Dead Square, Elozeal, MT, Puerto Rico'),
('Starwood Hotels & Resorts Worldwide Inc','1002 Tapto Trail, Papibhi, MT, Turkmenistan'),
('Allegheny Technologies Incorporated','1727 Tahif Park, Mesutco, MO, Christmas Island'),
('Pier 1 Imports Inc.','194 Zibi Ridge, Nervuuz, CA, Bahamas'),
('Pennzoil-Quaker State Company','1082 Nuwa Glen, Aruvowsid, NJ, France'),
('Bell Microproducts Inc.','1918 Ruvse Glen, Akotinve, FL, Réunion'),
('Progress Energy Inc','360 Puzef River, Mekgiris, NC, Gambia'),
('IMS Health Inc.','1305 Ukdus River, Iluhegnir, VA, Sudan'),
('Adelphia Communications Corporation','1200 Sefa Path, Cijodpi, TN, Samoa'),
('Capital One Financial Corp.','669 Edwoc Plaza, Cuehotiz, MT, Equatorial Guinea'),
('Publix Super Markets Inc.','1543 Cedih Key, Obenicu, MO, Macedonia'),
('Shopko Stores Inc','188 Sithi Glen, Koihkez, MT, Jersey'),
('Aetna Inc.','1011 Dawuh River, Ifaonzu, FL, Uruguay'),
('VF Corporation','149 Saste Way, Onkuzar, IL, Guernsey'),
('Vulcan Materials Company','1333 Nasun Drive, Tomjefsal, NH, Sweden'),
('Hershey Foods Corp.','1085 Ivge Extension, Udijewdis, NH, Syria'),
('Pepsi Bottling Group Inc.','1207 Miceg Extension, Cuzijdo, IL, Nicaragua'),
('Equifax Inc.','1409 Rorne Path, Lenbafpal, IN, Venezuela'),
('TravelCenters of America Inc.','1476 Ejaaj Junction, Lapkeko, WY, Kyrgyzstan'),
('Owens & Minor Inc.','1349 Natfa Extension, Ajrikiz, PA, Nepal'),
('Quest Diagnostics Inc.','949 Dirtim Park, Wucozeed, WY, Netherlands'),
('Rent A Center Inc','1357 Ecnu Point, Nopvalah, WA, Cayman Islands'),
('Beverly Enterprises, Inc.','196 Cisag Pass, Boecju, AR, Burkina Faso'),
('First National of Nebraska Inc.','1478 Semle Glen, Mabebe, NC, North Korea'),
('Banta Corporation','231 Giac Road, Tuburir, WY, Ascension Island'),
('Exelon Corporation','1501 Caaji Parkway, Nucubi, MA, Congo - Kinshasa'),
('Lam Research Corporation','1473 Wubon Road, Bussijini, FL, Azerbaijan'),
('Comerica Inc.','506 Dafzu Pass, Gasturram, TX, Guyana'),
('Union Planters Corp','539 Jajduc Junction, Nagiinu, WV, St. Vincent & Grenadines'),
('Dun & Bradstreet Inc.','804 Dituw Plaza, Ziguuve, VT, Mozambique'),
('Metals USA Inc.','1949 Bavsir Center, Kusamric, SC, Liberia'),
('US Oncology Inc','421 Tofir Point, Kercemda, MA, Vietnam'),
('StanCorp Financial Group Inc','768 Giwsa Boulevard, Ukelaclap, MI, Russia'),
('CMS Energy Corp.','818 Giki Heights, Zesabto, CO, Maldives'),
('Levi Strauss & Co.','1778 Uhudi Junction, Hutoiw, AR, Oman'),
('Flowserv Corp','411 Faddo View, Vejpaki, KS, Serbia'),
('Saks Inc','115 Pilis Key, Kizobo, VA, Argentina'),
('Unisys Corporation','1099 Hotfip Glen, Nornuhok, ND, Tunisia'),
('Allegheny Technologies Incorporated','842 Sovih River, Ulasehok, NC, Vanuatu'),
('Popular Inc','299 Vewap Glen, Dagcidod, MO, Zambia'),
('BJ Services Company','1234 Jivjez Park, Esjuvi, SD, British Indian Ocean Territory'),
('Ryerson Tull Inc','669 Cebpo Lane, Bifvuszin, SD, Gibraltar'),
('GenCorp Inc.','1024 Regat Point, Kidege, WI, Rwanda'),
('Riverwood Holding Inc.','1048 Huul Court, Kumwijuf, LA, New Zealand'),
('Echostar Communications Corporation','193 Vowi River, Alofofe, MS, Cayman Islands'),
('Loews Corporation','1827 Sobik Key, Wesakek, NY, Slovenia'),
('Cummins Inc.','510 Fezpa River, Nugobho, KS, Albania'),
('Gannett Co., Inc.','1301 Vefub Pass, Hirarna, VT, Macau SAR China'),
('Safeway Inc','69 Vaina Circle, Buridov, NM, Monaco'),
('Delphi Corp.','1780 Nodug Street, Oluvuawe, WV, South Sudan'),
('MGM Mirage','1531 Imhan Court, Wetagta, VA, Palestinian Territories'),
('E.I. Du Pont de Nemours and Company','911 Mukav Terrace, Icomibunu, LA, Philippines'),
('Anadarko Petroleum Corporation','356 Sorupi Path, Fasiwnew, AK, Oman'),
('CNF Inc.','268 Suev Manor, Raterful, TN, Zambia'),
('Cooper Industries Ltd.','326 Lele Plaza, Okuezepi, NE, Kyrgyzstan'),
('NorthWestern Corporation','319 Izusac Boulevard, Vomire, FL, U.S. Outlying Islands'),
('USA Interactive','1090 Ajtib Street, Zulewleg, LA, Eritrea'),
('Delphi Corp.','151 Esugej Extension, Kauliju, SD, Costa Rica'),
('C. H. Robinson Worldwide Inc.','246 Sipek Square, Oduvewwu, UT, South Sudan'),
('WestPoint Stevens Inc','1412 Nuzifi Place, Zapbawrev, FL, Central African Republic'),
('D.R. Horton Inc.','1080 Buja Pike, Waneboz, DE, Jersey'),
('ONEOK Inc','905 Atzef Junction, Widregda, OR, Botswana'),
('Xerox Corp','1275 Buhow Pass, Usogusjiv, WI, Czech Republic'),
('Hughes Supply Inc.','1418 Wasfuj Park, Ulvetew, DE, Guinea-Bissau'),
('Lands End Inc.','824 Bicha Manor, Hucehji, NV, Lesotho'),
('Agway Inc.','471 Temak Avenue, Sagciege, UT, Zambia'),
('Banknorth Group, Inc.','1265 Gizrop Heights, Efagza, AK, Greenland'),
('Unitrin Inc','1666 Rowvig Circle, Vadfefni, AK, Curaçao'),
('SCI Systems Onc.','1087 Wipegi Square, Odawaduw, WV, North Korea'),
('UAL Corporation','928 Zuhrob Extension, Mizfuzak, DE, Ireland'),
('Lands End Inc.','318 Rakig Court, Ohiatwi, VT, Hungary'),
('H.B. Fuller Company','676 Azko Highway, Paledad, UT, Switzerland'),
('Coventry Health Care Inc.','937 Ehuzol Boulevard, Vojoso, CT, Gambia'),
('Yellow Corporation','84 Dutid Trail, Uholaca, KY, Honduras'),
('Kellwood Company','1349 Secvus Place, Varhecih, IA, Albania'),
('Hon Industries Inc.','662 Veuca Junction, Pujbediw, TX, Anguilla'),
('American Water Works Company, Inc.','83 Pajul River, Doifasi, IL, Isle of Man'),
('Pro-Fac Cooperative Inc.','270 Nose Park, Kutumvi, OR, Svalbard & Jan Mayen'),
('Riverwood Holding Inc.','338 Heztu Court, Sohamanub, NV, Comoros'),
('ArvinMeritor, Inc.','1222 Kilme Street, Cicoda, ID, Bangladesh'),
('Cooper Tire & Rubber Co.','1389 Tusi River, Lucjazibu, FL, Kazakhstan'),
('Linens Things Inc.','1607 Pufo Road, Huikewa, NJ, Bermuda'),
('Nabors Industries Inc','1429 Utineh Pass, Onokinko, OR, Sri Lanka'),
('Tenneco Automotive Inc.','1548 Heto Parkway, Favopje, TX, Iceland'),
('SBC Communications Inc','325 Relti View, Ofouwaki, MO, Philippines'),
('Dow Chemical Company','342 Givmu River, Ruzleczar, WY, Cayman Islands'),
('ITT Industries Inc.','1744 Judna Turnpike, Toumti, VA, Burundi'),
('Arrow Electronics, Inc.','450 Hifo Grove, Efvibi, MD, South Korea'),
('Estee Lauder Companies Inc.','251 Ozacig Highway, Tezfesfu, MS, India'),
('Regis Corporation','258 Kaku Way, Johudato, AZ, Hong Kong SAR China'),
('Ryerson Tull Inc','204 Amubi Square, Noehlo, SC, British Indian Ocean Territory'),
('Felcor Lodging Trust Inc.','1055 Novi Street, Zisabueho, OR, São Tomé and Príncipe'),
('Brown Shoe Company, Inc.','717 Deso Extension, Tusuucu, SC, Niger'),
('Earthlink, Inc.','548 Wohac Heights, Deswegza, OK, Syria'),
('ChevronTexaco Corp.','879 Adba Loop, Pueduc, IN, Taiwan'),
('UnitedHealth Group Incorporated','753 Pugpol Turnpike, Bazfabbo, CO, Philippines'),
('Interstate Bakeries Corporation','1186 Zekpam River, Sowtawve, CA, Ghana'),
('SPX Corp','1406 Zumwu Heights, Fedinew, OK, Costa Rica'),
('Massey Energy Company','1178 Wite Drive, Fogujuj, GA, Belgium'),
('Marshall & Ilsley Corporation','352 Cugca Pass, Rahkustez, NY, Netherlands'),
('Weyerhauser Company','1813 Beaz Pass, Iwenruv, NH, Ethiopia'),
('Ames Department Stores, Inc.','1962 Ovhan Way, Wakowakuz, AK, Honduras'),
('Exide Technologies','1018 Luka Ridge, Vadrijkon, DE, U.S. Outlying Islands'),
('Lyondell Chemical Company','479 Vehi Center, Faicfus, PA, Tajikistan'),
('Solutia Inc','820 Pefib Heights, Ubdiffa, NE, Tonga'),
('Shaw Group Inc','140 Omme Parkway, Papfisu, HI, Madagascar'),
('National Semiconductor Corporation','1742 Beiri Boulevard, Nagugini, WV, Netherlands'),
('Trinity Industries Inc','1538 Oletip Loop, Erohuzsu, KS, Côte d Ivoire'),
('Cooper Tire & Rubber Co.','1332 Duwaku Park, Fehigi, MT, Mongolia'),
('WESCO International Inc','1141 Avugi Place, Oglija, AZ, Mauritania'),
('CMS Energy Corp.','238 Afido View, Kuvdutad, CT, Lebanon'),
('Equifax Inc.','572 Udoej Mill, Wefuwez, WY, Central African Republic'),
('Lennox International Inc.','792 Unuiv Boulevard, Zegunwow, NE, Guinea'),
('Terex Corp','541 Senca River, Oczawfev, WI, Romania'),
('Federal Mogul Corp.','1583 Famebi View, Oluuzaizu, KY, Czech Republic'),
('Regions Financial Corp.','1643 Buon Square, Jofnolaf, FL, Vanuatu'),
('Albertsons, Inc.','847 Gabala Turnpike, Ecebeom, IA, Zimbabwe'),
('Polaris Industries Inc.','730 Tevbe Center, Kobidni, AR, Finland'),
('Engelhard Corporation','1344 Jucwep Point, Azirujhuv, PA, Lebanon'),
('PNM Resources Inc','491 Ovuto Circle, Vengewon, KS, Ghana'),
('Sysco Corp','425 Neuga Terrace, Zakjitiri, NJ, Wallis & Futuna'),
('Cablevision Systems Corp','1985 Cule Street, Femorkek, TN, Portugal'),
('Jacobs Engineering Group Inc.','228 Felot Path, Nivvabkej, OK, Chile'),
('BorgWarner Inc.','1370 Jicja Place, Inunoco, CA, South Korea'),
('DST Systems, Inc.','1784 Buwi Path, Semokiat, WA, Åland Islands'),
('Cendant Corp','1637 Sehnil Extension, Daevunu, KS, Togo'),
('MGM Mirage','392 Dailo Terrace, Kiktook, RI, Madagascar'),
('Lockheed Martin Corporation','672 Ruiwo Pike, Cehaewu, IL, Mozambique'),
('Solutia Inc','28 Rewza Parkway, Tamliab, NH, Tonga'),
('Huntington Bancshares Inc.','249 Runfol Junction, Dobhejnin, WI, Russia'),
('Quanta Services Inc.','1874 Gougu Parkway, Aciwazude, ME, Kuwait'),
('Harsco Corp.','443 Edgah Point, Elnucme, HI, Seychelles'),
('The Boeing Company','475 Atlej Pike, Fidisup, DC, Thailand'),
('Pall Corp','257 Gulni Street, Zuhetvul, CA, U.S. Virgin Islands'),
('TruServ Corporation','1418 Barip Lane, Cehdekbur, AZ, India'),
('Synovus Financial Corp.','418 Zoeba Place, Uznidadu, DE, Macau SAR China'),
('Lennar Corporation','506 Rinah View, Kellogeb, WA, Nepal'),
('Genesis Health Ventures Inc.','1216 Nura Heights, Usapohi, LA, Hungary'),
('Zale Corporation','354 Puliw Manor, Ruetife, UT, Uzbekistan'),
('LSI Logic Corporation','134 Teiwu River, Icdaltu, NE, Iceland'),
('Sierra Pacific Resources','237 Itka Highway, Nuvdakdul, PA, Guyana'),
('Nvidia Corp','1584 Hebhe Manor, Miilwu, WI, Greenland'),
('Micron Technology Inc.','1553 Icuabo Heights, Kawtepka, AL, Isle of Man'),
('Bowater Incorporated','294 Kakod Trail, Dabmuwnij, WY, St. Vincent & Grenadines'),
('Wisconsin Energy Corporation','629 Sukvo Court, Miduvib, LA, Liechtenstein'),
('Trans World Entertainment Corp.','572 Rimju Extension, Nesmasu, WV, Martinique'),
('Wachovia Corporation','1295 Cuwlu Glen, Hifivudo, HI, Turkmenistan'),
('General Motors Corporation','1293 Nugrek Manor, Idojubta, MA, Switzerland'),
('BJs Wholesale Club, Inc.','82 Luap Loop, Isumakan, NJ, U.S. Virgin Islands'),
('Fleming Companies Inc.','534 Ceni Glen, Vofazo, ID, St. Pierre & Miquelon'),
('Harman International Industries Inc.','434 Movab Parkway, Tijufhih, AR, Tajikistan'),
('Marsh Supermarkets Inc.','510 Gefof View, Gafuhi, MO, Tonga'),
('Paychex Inc','1497 Hubog Square, Vajojo, UT, French Guiana'),
('Hasbro Inc.','126 Cosa Boulevard, Ipicofcoj, IA, Uganda'),
('PNM Resources Inc','1289 Hibe Pass, Iluutop, MN, Ukraine'),
('Sears Roebuck & Co','1308 Juhjid Court, Sozibap, KY, Congo - Brazzaville'),
('URS Corporation','1652 Usra Heights, Mifateuz, MO, Romania'),
('Provident Financial Group','1581 Jahgur Parkway, Ejofeofo, AK, Belize'),
('IMS Health Inc.','270 Atago Mill, Bowsujeh, OR, Bahrain'),
('Fidelity National Financial Inc.','133 Afnu Road, Athoih, ND, Azerbaijan'),
('Park Place Entertainment Corp','1427 Wowkow Plaza, Mizahifo, IN, Kazakhstan'),
('Burlington Industries, Inc.','1631 Amuebe River, Hugiwje, NJ, Madagascar'),
('NiSource Inc','254 Memi Junction, Juwtofjom, RI, Cayman Islands'),
('Mohawk Industries Inc.','1615 Otza Way, Celfijre, MT, Curaçao'),
('Owens Corning','1001 Koho Point, Foakpor, AZ, Sri Lanka'),
('W.W. Grainger Inc','101 Jeovi Junction, Nijmujki, AL, Tonga'),
('EGL Inc.','338 Wiefu Place, Minbocma, NV, Jersey'),
('M & T Bank Corporation','1101 Sajo Plaza, Izuvubip, IL, Bolivia'),
('Old Republic International Corp.','1942 Ajiwo Grove, Asujoctej, PA, Bahrain'),
('Quantum Corp','1938 Kirof Point, Ziiwir, VA, Grenada'),
('Providian Financial Corp.','778 Sotip Court, Verhezi, OR, Rwanda'),
('Conseco Inc.','1965 Zebij Parkway, Ihzune, OK, Kyrgyzstan'),
('Exide Technologies','986 Ropek Boulevard, Dazwojuc, SD, Togo'),
('Staples Inc','402 Buuf Pass, Nenwugfer, OH, Puerto Rico'),
('FPL Group Inc.','1471 Ekeboh Path, Pudolti, VT, Brunei'),
('Champion Enterprises Inc.','241 Dujgo Way, Zezsoin, SD, Bhutan'),
('Boise Cascade Corporation','947 Duwo Avenue, Ofgajfa, FL, Mozambique'),
('Charter One Financial Inc.','36 Isba Point, Bokiviv, DC, Tuvalu'),
('Marathon Oil Corporation','477 Kuber Trail, Fusahaco, ND, Kyrgyzstan'),
('Storage Technology Corporation','96 Jicumu River, Tihdallus, MO, Kuwait'),
('Owens-Illinois Inc','546 Gumiho Circle, Levujmis, SC, Singapore'),
('World Fuel Services Corporation','333 Dinoz Key, Iguhuok, AZ, Diego Garcia'),
('Cintas Corp.','1213 Mokiv Ridge, Cozcabege, DC, Bahamas'),
('The Boeing Company','1498 Dokka Circle, Cemurufe, WI, Palau'),
('Omnicare Inc','914 Doav Manor, Movwiclin, MS, Senegal'),
('Capital One Financial Corp.','1281 Wasla Path, Cegibe, NC, Curaçao'),
('CBRL Group Inc.','1990 Andot Road, Nasracdij, ID, Ethiopia'),
('Office Depot Inc.','167 Nakso Key, Marupbut, IL, Kosovo'),
('Primedia Inc','719 Gukiw View, Duwdoti, VA, Laos'),
('ACT Manufacturing Inc.','689 Kota Highway, Tetjulno, RI, Guyana'),
('UST Inc','1875 Gepad Heights, Focbagij, MD, Qatar'),
('Cabot Corp','489 Hecpez Avenue, Tupgiwev, GA, Kenya'),
('Jack In The Box Inc.','902 Nappeh Avenue, Otivuir, TN, Niue'),
('Morgan Stanley Dean Witter & Co.','426 Doel Grove, Nuicabuf, NM, Uganda'),
('RGS Energy Group Inc','445 Hape Terrace, Jodigwo, NE, Poland'),
('Xcel Energy Inc','657 Boonu Lane, Soctihaj, FL, Tanzania'),
('Revlon Inc','1719 Ivdo Terrace, Ciptildok, MA, Ukraine'),
('Tektronix Inc','1250 Guzfev Plaza, Ojocupot, IL, Tunisia'),
('Arkansas Best Corporation','1946 Wudok Way, Awjueg, NV, Guatemala'),
('Alberto-Culver Company','1207 Cutu Heights, Sasmizol, CO, Syria'),
('United Technologies Corporation','247 Ruiza Key, Noiwned, ID, U.S. Virgin Islands'),
('Gannett Co., Inc.','1090 Pafpe Pike, Parraugi, DE, Tajikistan'),
('BJ Services Company','729 Cuspa Parkway, Gejore, CT, Côte d Ivoire'),
('Briggs & Stratton Corporation','481 Mocus Center, Ucehagtal, KS, Laos'),
('Citizens Communications Co.','852 Demo Glen, Hepzaugi, TN, Costa Rica'),
('Ross Stores Inc','825 Nacmuk Pike, Ekjereni, NY, Romania'),
('Viad Corp','1603 Afkis Street, Fabusjad, NJ, Nauru'),
('Mail-Well Inc.','294 Zasuju View, Wokmuzzed, RI, French Southern Territories'),
('Hilton Hotels Corp.','707 Ragbec Mill, Gizujud, GA, North Korea'),
('Burlington Industries, Inc.','698 Lalob Highway, Nipijol, SC, St. Helena'),
('United Technologies Corporation','1726 Rira Plaza, Vimfodog, KY, St. Pierre & Miquelon'),
('Coca-Cola Enterprises Inc.','1102 Gunaj Park, Russoun, NV, Ireland'),
('Fortune Brands Inc.','1920 Nopo Turnpike, Amlaloj, OK, Nauru'),
('3Com Corp','1789 Onofi Turnpike, Awcapom, SD, Costa Rica'),
('Principal Financial Group Inc.','1528 Dihli Heights, Uniguwu, NJ, Libya'),
('Benchmark Electronics, Inc.','1781 Towoz Avenue, Tikafsu, NJ, Croatia'),
('Occidental Petroleum Corp','1058 Vipo Manor, Kajlumvum, MO, Mauritania'),
('Furniture Brands International Inc.','306 Emmir Way, Zejkilac, IA, Laos'),
('Duke Energy Corp','305 Kiti Point, Mihbukom, ME, Lithuania'),
('Maxtor Corporation','21 Devri Grove, Ewolrac, WY, Belize'),
('Capital One Financial Corp.','1720 Dapheg Point, Jimkeor, MT, St. Lucia'),
('Pulte Homes Inc','30 Bigus Trail, Apaawije, OK, Senegal'),
('Constellation Brands Inc.','1616 Vabsaj Turnpike, Islihji, UT, Solomon Islands'),
('Cincinnati Financial Corp.','1212 Fumve Turnpike, Hiogkam, IN, Estonia'),
('Mellon Financial Corporation','306 Naiza Road, Cifputfat, MD, Guadeloupe'),
('Landstar System Inc.','1544 Tapas Boulevard, Duwzaci, PA, Tunisia'),
('Airborne, Inc.','671 Cucriw Circle, Mukgapol, HI, Norway'),
('Washington Post Co.','913 Rajfot Place, Soamum, MO, Burkina Faso'),
('Mercury General Corporation','1447 Padrup Turnpike, Juhbigato, NH, Trinidad & Tobago'),
('Reliant Energy Inc.','1586 Idres Point, Eciuripu, WY, Belarus'),
('Cigna Corp','1634 Wihi Mill, Gebaonu, VT, Kenya'),
('H.B. Fuller Company','1380 Jonnu Parkway, Pawekev, TN, Palestinian Territories'),
('Navistar International Corporation','508 Zufni View, Difiik, TN, Moldova'),
('Trinity Industries Inc','591 Humuv Terrace, Cehvekep, GA, South Korea'),
('Unitrin Inc','1492 Ohhoh River, Tietteb, PA, Venezuela'),
('Toys Us Inc','1076 Gooti Way, Jogoghom, UT, Cyprus'),
('K-Mart Corp.','1473 Zaznar Road, Bapudediz, PA, Guinea'),
('America West Holdings Corporation','1318 Haktec Trail, Tilupa, HI, Christmas Island'),
('Gemstar-TV Guide International Inc.','353 Mifo View, Femilus, AL, Hong Kong SAR China'),
('Rent A Center Inc','1222 Luros Circle, Zeweci, AL, Eritrea'),
('CBRL Group Inc.','595 Riize Way, Tahikuuso, KY, Chile'),
('Scana Corp.','1272 Igre Place, Hoghemgis, OK, Zimbabwe'),
('Dollar Tree Stores, Inc.','1360 Naisa Street, Vutnihnag, UT, Tuvalu'),
('Georgia Gulf Corporation','770 Dokre Loop, Devtelo, CT, Macau SAR China'),
('US Airways Group Inc','937 Jean Street, Juhiudu, NY, Egypt'),
('Mirant Corporation','1693 Foam Parkway, Icgaur, NC, Cape Verde'),
('Leggett & Platt Inc.','313 Huji Boulevard, Awivojipe, NM, Hong Kong SAR China'),
('Metaldyne Corporation','835 Coccu Glen, Wajajdu, MT, Panama'),
('Xcel Energy Inc','1869 Evaw Extension, Matosci, NM, Iceland'),
('UST Inc','762 Heug Junction, Ligrofof, MD, Samoa'),
('DaVita Inc.','1309 Ococu Loop, Zijicuf, GA, Afghanistan'),
('Federal Express Corp.','140 Hote Street, Nocobug, AZ, Diego Garcia'),
('ONEOK Inc','1846 Biela Road, Kiovora, MA, Japan'),
('Wendys International Inc','279 Moclaf Center, Vuurdo, NH, Nigeria'),
('KPMG Consulting Inc.','175 Upidu Terrace, Fugcoeh, SD, Tokelau'),
('Nike Inc','719 Muji Avenue, Gegfafi, UT, Barbados'),
('Northeast Utilities System','251 Okuk Center, Mollogopo, ND, Ecuador'),
('Phelps Dodge Corp.','648 Polo Boulevard, Piutor, MI, Tanzania'),
('Supervalu Inc','1176 Fuge Avenue, Wadezrih, MT, American Samoa'),
('Felcor Lodging Trust Inc.','1995 Ureb Point, Ranivwig, ND, Canary Islands'),
('U.S. Industries Inc.','1004 Gavi Trail, Reksuwat, NE, Hong Kong SAR China'),
('American Standard Companies Inc.','14 Zivvu Key, Ritegfuv, AL, Pitcairn Islands'),
('Cadence Design Systems, Inc.','1751 Cujes Glen, Ocbodzam, ID, Canada'),
('SunGard Data Systems Inc.','708 Tifu Manor, Okikitiz, KY, Liechtenstein'),
('Budget Group, Inc.','1142 Loeje Point, Fiikoel, SC, Caribbean Netherlands'),
('PETsMART Inc','1624 Vete Mill, Nifjelo, ME, Greece'),
('Chiquita Brands International Inc.','574 Jicap Lane, Taggevwu, FL, Comoros'),
('DTE Energy Co.','1474 Ewac Street, Duvipucug, MA, Niue'),
('McKesson Corporation','101 Meji Center, Vovlidase, SC, Cambodia'),
('Bethlehem Steel Corporation','105 Futfuk Street, Omunebusu, NJ, Switzerland'),
('Kelly Services Inc.','1180 Sihiw Loop, Gorwicto, MI, Pitcairn Islands'),
('Stewart Information Services Corp','1323 Peaz Terrace, Waelnar, SD, Diego Garcia'),
('Darden Restaurants Inc.','957 Bozi Path, Idjovbi, FL, Guadeloupe'),
('Pantry Inc','877 Vemuc Lane, Aftafad, AZ, Switzerland'),
('Administaff, Inc.','55 Urufug Circle, Othoges, ND, Tanzania'),
('UGI Corporation','111 Lairu Park, Fucovimit, NH, Norfolk Island'),
('Kemet Corp.','1063 Fotsu Key, Vaafeiv, NJ, South Korea'),
('International Business Machines Corp.','378 Zejek River, Togewha, ME, Austria'),
('PepsiCo Inc.','306 Duena Ridge, Efpozlav, TX, Thailand'),
('Vulcan Materials Company','343 Nefut Lane, Vutujhe, FL, Vietnam'),
('Cinergy Corp.','1056 Rumob Pass, Edwusij, NY, Ghana'),
('BJ Services Company','1053 Nomsak Turnpike, Weemilog, CO, New Zealand'),
('Johnson Controls Inc.','1813 Piszif Parkway, Afoozopuf, NJ, Dominica'),
('TransMontaigne Inc','1734 Zikzo Glen, Reliar, CO, Christmas Island'),
('Limited Inc.','167 Cugu Key, Riekoro, AL, Guyana'),
('Dean Foods Company','943 Duhu Trail, Suzhuri, VT, Kyrgyzstan'),
('Eli Lilly and Company','1992 Garwi Avenue, Cizufuw, KS, Syria'),
('Fiserv Inc.','665 Bipac Street, Vimmire, OR, Bahamas'),
('Beverly Enterprises, Inc.','1642 Lugvo Avenue, Ejucocja, AZ, Zambia'),
('NorthWestern Corporation','1957 Puzite Park, Jitjoftaz, ME, Ascension Island'),
('Hercules Inc.','282 Acabo Pass, Lomcaweh, MA, Djibouti'),
('Southwest Gas Corp','185 Tokun Highway, Maepsur, PA, Guatemala'),
('Abercrombie & Fitch Co.','1535 Enguv Trail, Zojisiv, NM, Slovenia'),
('National Semiconductor Corporation','361 Mejib View, Nuvhouke, VA, Cambodia'),
('Penn Traffic Co.','553 Cica Terrace, Lafbusti, DC, Western Sahara'),
('Wisconsin Energy Corporation','568 Eheob View, Wegkavta, IA, British Virgin Islands'),
('Schering-Plough Corp','1324 Celan Heights, Piguac, NH, British Indian Ocean Territory'),
('Ace Hardware Corporation','988 Kinaj Lane, Noefzo, WY, Maldives'),
('Ivax Corp.','1470 Feugo Trail, Anigehri, AZ, Sweden'),
('Enron Corp.','242 Rugguc Way, Battipih, DE, Paraguay'),
('FirstEnergy Corp.','1130 Vamul Path, Putnoew, VA, Argentina'),
('Avaya Inc.','1829 Najoh Court, Vuhifohim, MT, St. Kitts & Nevis'),
('General Dynamics Corporation','1013 Giom Avenue, Inoveeb, ME, Greece'),
('The AES Corporation','1410 Calapo Path, Ceenotaj, RI, Gibraltar'),
('Omnicom Group','520 Iceizo Ridge, Mecpahol, IN, Turks & Caicos Islands'),
('St. Paul Cos.','1575 Bepotu Way, Izsavdob, RI, Russia'),
('Saks Inc','1361 Towaf Boulevard, Nefcumas, CT, Guyana'),
('Encompass Services Corporation','1340 Mitur Circle, Gopewo, ND, Bulgaria'),
('Mail-Well Inc.','1774 Duib Parkway, Behzolip, AR, Netherlands'),
('Gap Inc.','519 Keja Center, Neelegu, NC, Laos'),
('Bank of America Corporation','921 Bito Heights, Osauztoj, MO, Kosovo'),
('Advance Auto Parts, Inc.','1197 Owele River, Wipobgut, CO, Tajikistan'),
('Varco International Inc','1109 Filoj Path, Rilahvo, OK, Ascension Island'),
('Tribune Company','512 Gemmi Heights, Wakhiwfi, RI, Marshall Islands'),
('Sunoco Inc.','1378 Ecodah Road, Migkikef, OK, Denmark'),
('TRW Inc','268 Zefo View, Sefgebe, AL, Laos'),
('The Neiman Marcus Group Inc.','638 Muca Trail, Sodubcor, OR, France'),
('Cabot Corp','33 Celum Park, Kimieno, NM, Malaysia'),
('Toro Company','1742 Mibe Mill, Ufotadu, ME, Liberia'),
('UAL Corporation','1602 Lebcug Turnpike, Fiahsuz, VA, Hungary'),
('Xilinx Inc','1596 Rukuj Avenue, Remepa, AR, Turkey'),
('Gannett Co., Inc.','1183 Senota Path, Hiliram, MI, Cyprus'),
('Ohio Casualty Corp.','1319 Ledan Parkway, Pesitu, MO, Norfolk Island'),
('Eastman Chemical Company','610 Mafo Plaza, Otcotva, NM, Belgium'),
('Trump Hotels & Casino Resorts Inc.','1852 Laza Way, Suirdi, MO, Finland'),
('Interpublic Group of Companies Inc.','159 Pazfod Mill, Jovlawaje, CA, Burkina Faso'),
('Landstar System Inc.','1122 Rite Drive, Givigawo, WV, Andorra'),
('Delta Air Lines Inc.','472 Acmav Parkway, Fedvepac, ND, Tristan da Cunha'),
('Compuware Corp.','1316 Doca Junction, Wuavoriz, MO, Gambia'),
('Brunswick Corporation','1934 Vohlat Plaza, Ijvizse, UT, Bosnia & Herzegovina'),
('Adelphia Communications Corporation','1499 Mefi Highway, Fizafah, NY, Cambodia'),
('Owens-Illinois Inc','594 Nofju Manor, Puppuvebo, DC, Malta'),
('Loews Corporation','1602 Cimbaw View, Kekzipoc, CA, Guinea'),
('AMERCO','1586 Ofre Boulevard, Komsuzoz, NV, Western Sahara'),
('Administaff, Inc.','1875 Hosu Terrace, Anejisut, IL, Haiti'),
('Protective Life Corp','818 Owedof Parkway, Icafecvu, KS, Finland'),
('DTE Energy Co.','396 Dosihe Park, Jucefas, IL, Paraguay'),
('Coca-Cola Enterprises Inc.','628 Peife Junction, Forvurid, FL, United Arab Emirates'),
('Applied Materials, Inc.','1546 Vacog Key, Cadanale, WA, Honduras'),
('Wakenhut Corporation','166 Lalus Way, Dawfuzi, FL, Azerbaijan'),
('Kelly Services Inc.','281 Velu Pass, Suzavil, IL, Cuba'),
('Sequa Corp','1923 Ejadu Turnpike, Epwihdof, NM, Belarus'),
('Weatherford International Inc','635 Amuuv Road, Jaidauz, MA, St. Barthélemy'),
('Rock-Tenn Co','1284 Ilakiv Highway, Rofbefpo, MI, Diego Garcia'),
('Raymond James Financial Inc.','1310 Biras Mill, Zectupad, AZ, Nigeria'),
('Jefferson-Pilot Co.','1281 Ofhu Extension, Uvkafe, CT, Dominican Republic'),
('Burlington Coat Factory Warehouse Corporation','231 Felwo Parkway, Mathukon, NC, Anguilla'),
('USG Corporation','987 Somju Turnpike, Wuleftaj, OH, St. Helena'),
('Southwest Gas Corp','765 Nelhet Boulevard, Opaihiman, IN, Madagascar'),
('OfficeMax Inc','939 Meoco Ridge, Cuogsok, NM, Senegal'),
('Principal Financial Group Inc.','1584 Pecip Grove, Acateuwe, WV, Mauritius'),
('Dynegy Inc.','1604 Gera Mill, Sipaga, ID, Austria'),
('Phoenix Companies Inc','1496 Mufil Square, Abobihdo, IL, Kiribati'),
('Emerson Electric Co.','172 Tiva Place, Zozpime, ID, Bolivia'),
('Murphy Oil Corporation','177 Juow Key, Kogfovhul, IN, Finland'),
('Lockheed Martin Corporation','132 Etzan Loop, Halpefu, LA, Suriname'),
('Pier 1 Imports Inc.','1814 Mohi Junction, Etolafu, IL, Somalia'),
('Molex Incorporated','1253 Ovje Parkway, Tilgirhoz, OK, Vatican City'),
('Foamex International Inc','1924 Fiena Way, Nonvosili, NC, Sint Maarten'),
('Vectren Corporation','1663 Kusog Circle, Kumogo, CA, Laos'),
('Maxim Integrated Products Inc.','1783 Mogpo Drive, Mumowji, MT, Angola'),
('Nvidia Corp','1458 Kejzi Square, Zejaiwe, CA, Iran'),
('Community Health Systems Inc.','621 Ceflo Avenue, Sugici, MD, Jersey'),
('Ecolab Inc.','391 Ujneb Circle, Woijusew, MO, Greece'),
('Qwest Communications Intl Inc','1124 Irar Grove, Wafuljut, MA, Ghana'),
('PNC Financial Services Group Inc.','1879 Tiuna Trail, Tejahuos, VT, St. Vincent & Grenadines'),
('Eastman Chemical Company','622 Ijvib Way, Rettownog, IA, Chile'),
('PacifiCare Health Systems Inc','1325 Respul Square, Avolataf, RI, Wallis & Futuna'),
('Health Net Inc.','826 Komat Mill, Jukuhsuk, MO, Micronesia'),
('Gap Inc.','1428 Netoc Ridge, Refoin, CA, Finland'),
('Aon Corporation','131 Lopi River, Ozauciliw, GA, Cameroon'),
('Lear Corporation','1294 Sapet Place, Belufa, MI, São Tomé and Príncipe'),
('Harman International Industries Inc.','1315 Bapew Manor, Fefucsul, RI, Togo'),
('Paccar Inc','1124 Uraano Plaza, Comoksim, VA, St. Barthélemy'),
('TXU Corp','1040 Sutman Mill, Elinufab, IA, Bosnia & Herzegovina'),
('Air Products and Chemicals, Inc.','271 Gemju Key, Jugwimuz, CO, Tokelau');
